---
- name: Install Git on AWS EC2
  hosts: aws
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Verify Git installation
      command: git --version
      register: git_version
      changed_when: false

    - name: Display Git version
      debug:
        var: git_version.stdout
