---
- name: Install Jenkins on AWS EC2
  hosts: aws
  become: true

  tasks:

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: "0644"

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Add jenkins to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Create .kube directory
      file:
        path: /var/lib/jenkins/.kube
        owner: jenkins
        group: jenkins
        mode: "0700"
        state: directory

    - name: Copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        remote_src: yes
        dest: /var/lib/jenkins/.kube/config
        owner: jenkins
        group: jenkins
        mode: "0600"

    - name: Replace localhost with private IP
      replace:
        path: /var/lib/jenkins/.kube/config
        regexp: '127\.0\.0\.1|localhost'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: Create systemd override directory
      file:
        path: /etc/systemd/system/jenkins.service.d
        state: directory

    - name: Configure Jenkins environment
      copy:
        dest: /etc/systemd/system/jenkins.service.d/override.conf
        content: |
          [Service]
          Environment="KUBECONFIG=/var/lib/jenkins/.kube/config"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
        enabled: yes

    - name: Wait for Jenkins
      wait_for:
        port: 8080
        timeout: 180
